config/routes.rb
First::Application.routes.draw do

  get "users/new"

  root :to => "pages#home"
  
  match '/contact', :to => 'pages#contact'  
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  

 

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end

  def contact
  @title = "Contact"
  end
  
  def about
  @title = "About"
  end
  
  def help
  @title= "Help"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @title= "Sign Up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 #Return a title on per page basis
 
 def title
  base_title = "Microblogging App"
   if @title.nil?
     base_title
	# else
	 "#{base_title} | #{@title}"
	 end
	 end
 
 def logo
 image_tag("logo.png", :alt => "Sample app" , :class => "round" )
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
 <nav class = "round">
  <ul>
    <li> <%= link_to "About", about_path %></li>
	<li> <%= link_to "Contact", contact_path %></li>
	<li> <%= link_to "Git Repo", 'https://github.com/piy9/Twitter_clone', :target=>"_blank" %></li>
	<li> <%= link_to "Rails Tutorial", 'http://railstutorial.org', :target=>"_blank"  %></li>
	</ul>
</nav>
</footer>
	

app/views/layouts/_header.html.erb
<header>
	  <%= link_to logo,root_path %>
	 <nav class = "round">
	 
	 
	  <ul>
	  
	   <li> <%= link_to "Home", root_path %></li>
	   <li> <%= link_to "Help", help_path %></li>
	   <li> <%= link_to "Sign in", '#' %></li>
	  </ul> 
	  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
 <script src = "http://html5shiv.googlecode.com/svn/truck/html5.js"></script>
 <![endif]-->
 <%= stylesheet_link_tag 'blueprint/screen' , :media => 'screen' %>
 <%= stylesheet_link_tag 'blueprint/print' , :media=> 'print' %>
 <!--[if lt IE 8]>
 <%= stylesheet_link_tag 'blueprint/ie' %>
 <![endif]-->
 <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title> <%= @title %></title>
 <%= csrf_meta_tag %>
 <%= render 'layouts/stylesheets' %>
 </head>
 <body>
   <div class="container">
    <%= render 'layouts/header' %>
	<section class ="round">
	   <%= yield %>
     </section>
	 <%= render 'layouts/footer' %>
	 </div> 
</body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>
This is the home page for the Micro blogging App. This is developed by <a href="https://www.facebook.com/piyushkhemka" target="_blank" >Piyush Khemka</a>
This app was inspired from Micheal Hartl's tutorial on Ruby on Rails.</p>

<p><i>
This app is not intended for commercial use.
<br/>
<p>*But feel free to explore around*</i></p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<p>
You can message me on <a href="https://www.facebook.com/piyushkhemka">facebook</a>
</p>
<br/>

app/views/pages/help.html.erb
<h1> Help </h1>
<p> 
 If you want to make your own twitter clone, then checkout <a href="http://railstutorial.org/help"> Rails tutorial help page</a>
 </p>
 
 

app/views/pages/home.html.erb
<h1>KHEMS</h1>
<p>
This is the home page for Khems - A Micro blogging App. It is similar to Twitter.
</p>

<%= link_to "Sign up now!" , signup_path, :class => "signup round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>